apiVersion: apps/v1
kind: deployment
metadata:
  name:  spring-boot-devopslab-deployment
spec:
  selector:
    matchLabels:
      app: blog
    replicas: 2
    template:
      metadata:
        labels:
          app: blog
      spec:
        containers:
          - name: blog
            image: rismi/devopsimage1
            imagePullPolicy: IfNotPresent
            ports:
              - containerPort: 8084